<?php  
$urls = array(
    'http://www.qufair.com/forum/detail/id/2678'
    'http://www.qufair.com/forum/detail/id/2677'
    'http://www.qufair.com/forum/detail/id/2676'
    'http://www.qufair.com/forum/detail/id/2675'
    'http://www.qufair.com/forum/detail/id/2674'
    'http://www.qufair.com/forum/detail/id/2673'
    'http://www.qufair.com/forum/detail/id/2656'
    'http://www.qufair.com/forum/detail/id/2658'
    'http://www.qufair.com/forum/detail/id/2668'
    'http://www.qufair.com/forum/detail/id/2667'
    'http://www.qufair.com/forum/detail/id/2666'
    'http://www.qufair.com/forum/detail/id/2665'
    'http://www.qufair.com/forum/detail/id/2657'
    'http://www.qufair.com/forum/detail/id/2669'
    'http://www.qufair.com/forum/detail/id/2672'
    'http://www.qufair.com/forum/detail/id/2659'
    'http://www.qufair.com/forum/detail/id/2664'
    'http://www.qufair.com/forum/detail/id/2670'
    'http://www.qufair.com/forum/detail/id/2663'
    'http://www.qufair.com/forum/detail/id/2662'
    'http://www.qufair.com/forum/detail/id/2661'
    'http://www.qufair.com/forum/detail/id/2660'
    'http://www.qufair.com/forum/detail/id/2655'
    'http://www.qufair.com/forum/detail/id/2652'
    'http://www.qufair.com/forum/detail/id/2651'
    'http://www.qufair.com/forum/detail/id/2650'
    'http://www.qufair.com/forum/detail/id/2649'
    'http://www.qufair.com/forum/detail/id/2648'
    'http://www.qufair.com/forum/detail/id/2647'
    'http://www.qufair.com/forum/detail/id/2646'
    'http://www.qufair.com/forum/detail/id/2645'
    'http://www.qufair.com/forum/detail/id/2644'
    'http://www.qufair.com/forum/detail/id/2643'
    'http://www.qufair.com/forum/detail/id/2642'
    'http://www.qufair.com/forum/detail/id/2641'
    'http://www.qufair.com/forum/detail/id/2640'
    'http://www.qufair.com/forum/detail/id/2639'
    'http://www.qufair.com/forum/detail/id/2638'
    'http://www.qufair.com/forum/detail/id/2637'
    'http://www.qufair.com/forum/detail/id/2635'
    'http://www.qufair.com/forum/detail/id/2636'
    'http://www.qufair.com/forum/detail/id/2634'
    'http://www.qufair.com/forum/detail/id/2615'
    'http://www.qufair.com/forum/detail/id/2614'
    'http://www.qufair.com/forum/detail/id/2613'
    'http://www.qufair.com/forum/detail/id/2611'
    'http://www.qufair.com/forum/detail/id/2610'
    'http://www.qufair.com/forum/detail/id/2609'
    'http://www.qufair.com/forum/detail/id/2608'
    'http://www.qufair.com/forum/detail/id/2602'
    'http://www.qufair.com/forum/detail/id/2607'
    'http://www.qufair.com/forum/detail/id/2606'
    'http://www.qufair.com/forum/detail/id/2596'
    'http://www.qufair.com/forum/detail/id/2605'
    'http://www.qufair.com/forum/detail/id/2604'
    'http://www.qufair.com/forum/detail/id/2603'
    'http://www.qufair.com/forum/detail/id/2601'
    'http://www.qufair.com/forum/detail/id/2600'
    'http://www.qufair.com/forum/detail/id/2599'
    'http://www.qufair.com/forum/detail/id/2597'
    'http://www.qufair.com/forum/detail/id/2598'
    'http://www.qufair.com/forum/detail/id/2595'
    'http://www.qufair.com/forum/detail/id/2594'
    'http://www.qufair.com/forum/detail/id/2593'
    'http://www.qufair.com/forum/detail/id/2581'
    'http://www.qufair.com/forum/detail/id/2582'
    'http://www.qufair.com/forum/detail/id/2584'
    'http://www.qufair.com/forum/detail/id/2586'
    'http://www.qufair.com/forum/detail/id/2585'
    'http://www.qufair.com/forum/detail/id/2587'
    'http://www.qufair.com/forum/detail/id/2590'
    'http://www.qufair.com/forum/detail/id/2589'
    'http://www.qufair.com/forum/detail/id/2589'
    'http://www.qufair.com/forum/detail/id/2591'
    'http://www.qufair.com/forum/detail/id/2583'
    'http://www.qufair.com/forum/detail/id/2588'
    'http://www.qufair.com/forum/detail/id/2577'
    'http://www.qufair.com/forum/detail/id/2578'
    'http://www.qufair.com/forum/detail/id/2580'
    'http://www.qufair.com/forum/detail/id/2579'
    'http://www.qufair.com/forum/detail/id/2574'
    'http://www.qufair.com/forum/detail/id/2575'
    'http://www.qufair.com/forum/detail/id/2576'
    'http://www.qufair.com/forum/detail/id/2573'
    'http://www.qufair.com/forum/detail/id/2571'
);
$api = 'http://data.zz.baidu.com/update?site=www.qufair.com&token=7PizC9BIruRR7UlJ';
$ch = curl_init();
$options =  array(
    CURLOPT_URL => $api,
    CURLOPT_POST => true,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POSTFIELDS => implode("\n", $urls),
    CURLOPT_HTTPHEADER => array('Content-Type: text/plain'),
);
curl_setopt_array($ch, $options);
$result = curl_exec($ch);
echo $result;
?>
