<?php
return array(
	'savepath' => 'attach',
	'wateron' => '1',
	'waterfile' => '/style/common/watermark.png',
	'watertext' => '第一互联',
	'waterplace' => '5',
	'wateralpha' => '0.40',
	'bgcolor' => '#FFFFFF',
	'max' => '5242880',
	'type' => array(
		'application/pdf',
		'application/octet-stream',
		'application/zip',
		'application/x-compress',
		'application/x-gtar',
		'application/x-gzip',
		'application/x-tar',
		'application/bzip2',
		'application/x-arj',
		'application/msword',
		'application/vnd.ms-excel',
		'application/vnd.ms-powerpoint',
		'application/x-photoshop',
		'application/x-shockwave-flash',
		'application/x-javascript',
		'application/postscript',
		'application/x-msmetafile',
		'application/x-lha',
		'application/x-rar-compressed',
		'image/gif',
		'image/png',
		'image/x-png',
		'image/jpeg',
		'image/pjpeg',
		'image/jpg',
		'image/bmp',
		'image/tiff',
		'image/x-pict',
		'application/ico',
		'audio/midi',
		'audio/wav',
		'audio/mpeg',
		'video/x-msvideo',
		'video/mpeg',
		'video/quicktime',
		'video/mp4',
		'application/octet-stream.mp4',
		'audio/amr',
		'audio/speex',
	),
);